/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface NoxEscrowReputationInterface extends Interface {
    getFunction(nameOrSignature: "UPGRADE_INTERFACE_VERSION" | "addCompletedMilestone" | "baseReputationHandle" | "factory" | "getReputation" | "initialize" | "owner" | "penalizeLostDispute" | "proxiableUUID" | "renounceOwnership" | "setBaseReputation" | "setFactory" | "transferOwnership" | "upgradeToAndCall"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "BaseReputationConfigured" | "FactoryUpdated" | "Initialized" | "OwnershipTransferred" | "ReputationUpdated" | "Upgraded"): EventFragment;

    encodeFunctionData(functionFragment: 'UPGRADE_INTERFACE_VERSION', values?: undefined): string;
encodeFunctionData(functionFragment: 'addCompletedMilestone', values: [AddressLike, BytesLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'baseReputationHandle', values?: undefined): string;
encodeFunctionData(functionFragment: 'factory', values?: undefined): string;
encodeFunctionData(functionFragment: 'getReputation', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'initialize', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'penalizeLostDispute', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'proxiableUUID', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'setBaseReputation', values: [BytesLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'setFactory', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'upgradeToAndCall', values: [AddressLike, BytesLike]): string;

    decodeFunctionResult(functionFragment: 'UPGRADE_INTERFACE_VERSION', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'addCompletedMilestone', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'baseReputationHandle', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'factory', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getReputation', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'initialize', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'penalizeLostDispute', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'proxiableUUID', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setBaseReputation', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setFactory', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'upgradeToAndCall', data: BytesLike): Result;
  }

  
    export namespace BaseReputationConfiguredEvent {
      export type InputTuple = [baseHandle: BytesLike];
      export type OutputTuple = [baseHandle: string];
      export interface OutputObject {baseHandle: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace FactoryUpdatedEvent {
      export type InputTuple = [oldFactory: AddressLike, newFactory: AddressLike];
      export type OutputTuple = [oldFactory: string, newFactory: string];
      export interface OutputObject {oldFactory: string, newFactory: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace InitializedEvent {
      export type InputTuple = [version: BigNumberish];
      export type OutputTuple = [version: bigint];
      export interface OutputObject {version: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ReputationUpdatedEvent {
      export type InputTuple = [freelancer: AddressLike, newReputation: BytesLike];
      export type OutputTuple = [freelancer: string, newReputation: string];
      export interface OutputObject {freelancer: string, newReputation: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UpgradedEvent {
      export type InputTuple = [implementation: AddressLike];
      export type OutputTuple = [implementation: string];
      export interface OutputObject {implementation: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface NoxEscrowReputation extends BaseContract {
    
    connect(runner?: ContractRunner | null): NoxEscrowReputation;
    waitForDeployment(): Promise<this>;

    interface: NoxEscrowReputationInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    UPGRADE_INTERFACE_VERSION: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    addCompletedMilestone: TypedContractMethod<
      [freelancer: AddressLike, payout: BytesLike, rating: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    baseReputationHandle: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    factory: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    getReputation: TypedContractMethod<
      [freelancer: AddressLike, ],
      [string],
      'view'
    >
    

    
    initialize: TypedContractMethod<
      [_factory: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    penalizeLostDispute: TypedContractMethod<
      [freelancer: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    proxiableUUID: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    setBaseReputation: TypedContractMethod<
      [_baseHandle: BytesLike, proof: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    setFactory: TypedContractMethod<
      [_newFactory: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    upgradeToAndCall: TypedContractMethod<
      [newImplementation: AddressLike, data: BytesLike, ],
      [void],
      'payable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'UPGRADE_INTERFACE_VERSION'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'addCompletedMilestone'): TypedContractMethod<
      [freelancer: AddressLike, payout: BytesLike, rating: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'baseReputationHandle'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'factory'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getReputation'): TypedContractMethod<
      [freelancer: AddressLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'initialize'): TypedContractMethod<
      [_factory: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'penalizeLostDispute'): TypedContractMethod<
      [freelancer: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'proxiableUUID'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setBaseReputation'): TypedContractMethod<
      [_baseHandle: BytesLike, proof: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setFactory'): TypedContractMethod<
      [_newFactory: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'upgradeToAndCall'): TypedContractMethod<
      [newImplementation: AddressLike, data: BytesLike, ],
      [void],
      'payable'
    >;

    getEvent(key: 'BaseReputationConfigured'): TypedContractEvent<BaseReputationConfiguredEvent.InputTuple, BaseReputationConfiguredEvent.OutputTuple, BaseReputationConfiguredEvent.OutputObject>;
getEvent(key: 'FactoryUpdated'): TypedContractEvent<FactoryUpdatedEvent.InputTuple, FactoryUpdatedEvent.OutputTuple, FactoryUpdatedEvent.OutputObject>;
getEvent(key: 'Initialized'): TypedContractEvent<InitializedEvent.InputTuple, InitializedEvent.OutputTuple, InitializedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'ReputationUpdated'): TypedContractEvent<ReputationUpdatedEvent.InputTuple, ReputationUpdatedEvent.OutputTuple, ReputationUpdatedEvent.OutputObject>;
getEvent(key: 'Upgraded'): TypedContractEvent<UpgradedEvent.InputTuple, UpgradedEvent.OutputTuple, UpgradedEvent.OutputObject>;

    filters: {
      
      'BaseReputationConfigured(bytes32)': TypedContractEvent<BaseReputationConfiguredEvent.InputTuple, BaseReputationConfiguredEvent.OutputTuple, BaseReputationConfiguredEvent.OutputObject>;
      BaseReputationConfigured: TypedContractEvent<BaseReputationConfiguredEvent.InputTuple, BaseReputationConfiguredEvent.OutputTuple, BaseReputationConfiguredEvent.OutputObject>;
    

      'FactoryUpdated(address,address)': TypedContractEvent<FactoryUpdatedEvent.InputTuple, FactoryUpdatedEvent.OutputTuple, FactoryUpdatedEvent.OutputObject>;
      FactoryUpdated: TypedContractEvent<FactoryUpdatedEvent.InputTuple, FactoryUpdatedEvent.OutputTuple, FactoryUpdatedEvent.OutputObject>;
    

      'Initialized(uint64)': TypedContractEvent<InitializedEvent.InputTuple, InitializedEvent.OutputTuple, InitializedEvent.OutputObject>;
      Initialized: TypedContractEvent<InitializedEvent.InputTuple, InitializedEvent.OutputTuple, InitializedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'ReputationUpdated(address,bytes32)': TypedContractEvent<ReputationUpdatedEvent.InputTuple, ReputationUpdatedEvent.OutputTuple, ReputationUpdatedEvent.OutputObject>;
      ReputationUpdated: TypedContractEvent<ReputationUpdatedEvent.InputTuple, ReputationUpdatedEvent.OutputTuple, ReputationUpdatedEvent.OutputObject>;
    

      'Upgraded(address)': TypedContractEvent<UpgradedEvent.InputTuple, UpgradedEvent.OutputTuple, UpgradedEvent.OutputObject>;
      Upgraded: TypedContractEvent<UpgradedEvent.InputTuple, UpgradedEvent.OutputTuple, UpgradedEvent.OutputObject>;
    
    };
  }