/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface NoxEscrowContractInterface extends Interface {
    getFunction(nameOrSignature: "activeMilestoneIndex" | "cUSDCToken" | "client" | "clientCancelRequested" | "factory" | "freelancer" | "freelancerCancelRequested" | "initialize" | "initializeEscrow" | "milestones" | "mutualCancel" | "raiseDispute" | "releaseMilestone" | "reputationRegistry" | "resolveDispute" | "reviewWindow" | "status" | "submitDeliverable" | "teeArbiter" | "totalMilestones"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "ContractInitialized" | "DeliverableSubmitted" | "DisputeOpened" | "DisputeResolved" | "Initialized" | "MilestoneApproved" | "MutualCancellationExecuted"): EventFragment;

    encodeFunctionData(functionFragment: 'activeMilestoneIndex', values?: undefined): string;
encodeFunctionData(functionFragment: 'cUSDCToken', values?: undefined): string;
encodeFunctionData(functionFragment: 'client', values?: undefined): string;
encodeFunctionData(functionFragment: 'clientCancelRequested', values?: undefined): string;
encodeFunctionData(functionFragment: 'factory', values?: undefined): string;
encodeFunctionData(functionFragment: 'freelancer', values?: undefined): string;
encodeFunctionData(functionFragment: 'freelancerCancelRequested', values?: undefined): string;
encodeFunctionData(functionFragment: 'initialize', values: [AddressLike, AddressLike, AddressLike, AddressLike, AddressLike, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'initializeEscrow', values: [BytesLike[], BytesLike[], BytesLike[], BytesLike[]]): string;
encodeFunctionData(functionFragment: 'milestones', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'mutualCancel', values?: undefined): string;
encodeFunctionData(functionFragment: 'raiseDispute', values?: undefined): string;
encodeFunctionData(functionFragment: 'releaseMilestone', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'reputationRegistry', values?: undefined): string;
encodeFunctionData(functionFragment: 'resolveDispute', values: [boolean]): string;
encodeFunctionData(functionFragment: 'reviewWindow', values?: undefined): string;
encodeFunctionData(functionFragment: 'status', values?: undefined): string;
encodeFunctionData(functionFragment: 'submitDeliverable', values: [BytesLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'teeArbiter', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalMilestones', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'activeMilestoneIndex', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'cUSDCToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'client', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'clientCancelRequested', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'factory', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'freelancer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'freelancerCancelRequested', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'initialize', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'initializeEscrow', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'milestones', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'mutualCancel', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'raiseDispute', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'releaseMilestone', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'reputationRegistry', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'resolveDispute', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'reviewWindow', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'status', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'submitDeliverable', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'teeArbiter', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalMilestones', data: BytesLike): Result;
  }

  
    export namespace ContractInitializedEvent {
      export type InputTuple = [client: AddressLike, freelancer: AddressLike, totalMilestones: BigNumberish];
      export type OutputTuple = [client: string, freelancer: string, totalMilestones: bigint];
      export interface OutputObject {client: string, freelancer: string, totalMilestones: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DeliverableSubmittedEvent {
      export type InputTuple = [milestoneIndex: BigNumberish, deliverableHash: BytesLike];
      export type OutputTuple = [milestoneIndex: bigint, deliverableHash: string];
      export interface OutputObject {milestoneIndex: bigint, deliverableHash: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DisputeOpenedEvent {
      export type InputTuple = [milestoneIndex: BigNumberish, requirementsHash: BytesLike, deliverableHash: BytesLike];
      export type OutputTuple = [milestoneIndex: bigint, requirementsHash: string, deliverableHash: string];
      export interface OutputObject {milestoneIndex: bigint, requirementsHash: string, deliverableHash: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DisputeResolvedEvent {
      export type InputTuple = [milestoneIndex: BigNumberish, ruledInFavorOfFreelancer: boolean];
      export type OutputTuple = [milestoneIndex: bigint, ruledInFavorOfFreelancer: boolean];
      export interface OutputObject {milestoneIndex: bigint, ruledInFavorOfFreelancer: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace InitializedEvent {
      export type InputTuple = [version: BigNumberish];
      export type OutputTuple = [version: bigint];
      export interface OutputObject {version: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MilestoneApprovedEvent {
      export type InputTuple = [milestoneIndex: BigNumberish];
      export type OutputTuple = [milestoneIndex: bigint];
      export interface OutputObject {milestoneIndex: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MutualCancellationExecutedEvent {
      export type InputTuple = [];
      export type OutputTuple = [];
      export interface OutputObject {};
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface NoxEscrowContract extends BaseContract {
    
    connect(runner?: ContractRunner | null): NoxEscrowContract;
    waitForDeployment(): Promise<this>;

    interface: NoxEscrowContractInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    activeMilestoneIndex: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    cUSDCToken: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    client: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    clientCancelRequested: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    factory: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    freelancer: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    freelancerCancelRequested: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    initialize: TypedContractMethod<
      [_client: AddressLike, _freelancer: AddressLike, _teeArbiter: AddressLike, _cUSDC: AddressLike, _reputationRegistry: AddressLike, _totalMilestones: BigNumberish, _reviewWindow: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    initializeEscrow: TypedContractMethod<
      [milestonePayouts: BytesLike[], payoutProofs: BytesLike[], milestoneReqs: BytesLike[], reqsProofs: BytesLike[], ],
      [void],
      'nonpayable'
    >
    

    
    milestones: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, string, string, bigint, boolean, boolean] & {requirementsHash: string, deliverableHash: string, payoutHandle: string, submissionTime: bigint, isSubmitted: boolean, isSettled: boolean }],
      'view'
    >
    

    
    mutualCancel: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    raiseDispute: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    releaseMilestone: TypedContractMethod<
      [rating: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    reputationRegistry: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    resolveDispute: TypedContractMethod<
      [ruleInFavorOfFreelancer: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    reviewWindow: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    status: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    submitDeliverable: TypedContractMethod<
      [_deliverableHash: BytesLike, proof: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    teeArbiter: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    totalMilestones: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'activeMilestoneIndex'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'cUSDCToken'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'client'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'clientCancelRequested'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'factory'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'freelancer'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'freelancerCancelRequested'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'initialize'): TypedContractMethod<
      [_client: AddressLike, _freelancer: AddressLike, _teeArbiter: AddressLike, _cUSDC: AddressLike, _reputationRegistry: AddressLike, _totalMilestones: BigNumberish, _reviewWindow: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'initializeEscrow'): TypedContractMethod<
      [milestonePayouts: BytesLike[], payoutProofs: BytesLike[], milestoneReqs: BytesLike[], reqsProofs: BytesLike[], ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'milestones'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, string, string, bigint, boolean, boolean] & {requirementsHash: string, deliverableHash: string, payoutHandle: string, submissionTime: bigint, isSubmitted: boolean, isSettled: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'mutualCancel'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'raiseDispute'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'releaseMilestone'): TypedContractMethod<
      [rating: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'reputationRegistry'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'resolveDispute'): TypedContractMethod<
      [ruleInFavorOfFreelancer: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'reviewWindow'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'status'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'submitDeliverable'): TypedContractMethod<
      [_deliverableHash: BytesLike, proof: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'teeArbiter'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'totalMilestones'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;

    getEvent(key: 'ContractInitialized'): TypedContractEvent<ContractInitializedEvent.InputTuple, ContractInitializedEvent.OutputTuple, ContractInitializedEvent.OutputObject>;
getEvent(key: 'DeliverableSubmitted'): TypedContractEvent<DeliverableSubmittedEvent.InputTuple, DeliverableSubmittedEvent.OutputTuple, DeliverableSubmittedEvent.OutputObject>;
getEvent(key: 'DisputeOpened'): TypedContractEvent<DisputeOpenedEvent.InputTuple, DisputeOpenedEvent.OutputTuple, DisputeOpenedEvent.OutputObject>;
getEvent(key: 'DisputeResolved'): TypedContractEvent<DisputeResolvedEvent.InputTuple, DisputeResolvedEvent.OutputTuple, DisputeResolvedEvent.OutputObject>;
getEvent(key: 'Initialized'): TypedContractEvent<InitializedEvent.InputTuple, InitializedEvent.OutputTuple, InitializedEvent.OutputObject>;
getEvent(key: 'MilestoneApproved'): TypedContractEvent<MilestoneApprovedEvent.InputTuple, MilestoneApprovedEvent.OutputTuple, MilestoneApprovedEvent.OutputObject>;
getEvent(key: 'MutualCancellationExecuted'): TypedContractEvent<MutualCancellationExecutedEvent.InputTuple, MutualCancellationExecutedEvent.OutputTuple, MutualCancellationExecutedEvent.OutputObject>;

    filters: {
      
      'ContractInitialized(address,address,uint256)': TypedContractEvent<ContractInitializedEvent.InputTuple, ContractInitializedEvent.OutputTuple, ContractInitializedEvent.OutputObject>;
      ContractInitialized: TypedContractEvent<ContractInitializedEvent.InputTuple, ContractInitializedEvent.OutputTuple, ContractInitializedEvent.OutputObject>;
    

      'DeliverableSubmitted(uint256,bytes32)': TypedContractEvent<DeliverableSubmittedEvent.InputTuple, DeliverableSubmittedEvent.OutputTuple, DeliverableSubmittedEvent.OutputObject>;
      DeliverableSubmitted: TypedContractEvent<DeliverableSubmittedEvent.InputTuple, DeliverableSubmittedEvent.OutputTuple, DeliverableSubmittedEvent.OutputObject>;
    

      'DisputeOpened(uint256,bytes32,bytes32)': TypedContractEvent<DisputeOpenedEvent.InputTuple, DisputeOpenedEvent.OutputTuple, DisputeOpenedEvent.OutputObject>;
      DisputeOpened: TypedContractEvent<DisputeOpenedEvent.InputTuple, DisputeOpenedEvent.OutputTuple, DisputeOpenedEvent.OutputObject>;
    

      'DisputeResolved(uint256,bool)': TypedContractEvent<DisputeResolvedEvent.InputTuple, DisputeResolvedEvent.OutputTuple, DisputeResolvedEvent.OutputObject>;
      DisputeResolved: TypedContractEvent<DisputeResolvedEvent.InputTuple, DisputeResolvedEvent.OutputTuple, DisputeResolvedEvent.OutputObject>;
    

      'Initialized(uint64)': TypedContractEvent<InitializedEvent.InputTuple, InitializedEvent.OutputTuple, InitializedEvent.OutputObject>;
      Initialized: TypedContractEvent<InitializedEvent.InputTuple, InitializedEvent.OutputTuple, InitializedEvent.OutputObject>;
    

      'MilestoneApproved(uint256)': TypedContractEvent<MilestoneApprovedEvent.InputTuple, MilestoneApprovedEvent.OutputTuple, MilestoneApprovedEvent.OutputObject>;
      MilestoneApproved: TypedContractEvent<MilestoneApprovedEvent.InputTuple, MilestoneApprovedEvent.OutputTuple, MilestoneApprovedEvent.OutputObject>;
    

      'MutualCancellationExecuted()': TypedContractEvent<MutualCancellationExecutedEvent.InputTuple, MutualCancellationExecutedEvent.OutputTuple, MutualCancellationExecutedEvent.OutputObject>;
      MutualCancellationExecuted: TypedContractEvent<MutualCancellationExecutedEvent.InputTuple, MutualCancellationExecutedEvent.OutputTuple, MutualCancellationExecutedEvent.OutputObject>;
    
    };
  }