/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface NoxEscrowFactoryInterface extends Interface {
    getFunction(nameOrSignature: "UPGRADE_INTERFACE_VERSION" | "allEscrows" | "cUSDCToken" | "createEscrow" | "escrowImplementation" | "escrowsCount" | "initialize" | "isEscrowContract" | "owner" | "proxiableUUID" | "renounceOwnership" | "reputationRegistry" | "reviewWindow" | "setEscrowImplementation" | "setReputationRegistry" | "setReviewWindow" | "setUSDCToken" | "transferOwnership" | "upgradeToAndCall"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "EscrowCreated" | "ImplementationUpdated" | "Initialized" | "OwnershipTransferred" | "ReputationRegistryUpdated" | "ReviewWindowUpdated" | "TokenUpdated" | "Upgraded"): EventFragment;

    encodeFunctionData(functionFragment: 'UPGRADE_INTERFACE_VERSION', values?: undefined): string;
encodeFunctionData(functionFragment: 'allEscrows', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'cUSDCToken', values?: undefined): string;
encodeFunctionData(functionFragment: 'createEscrow', values: [AddressLike, AddressLike, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'escrowImplementation', values?: undefined): string;
encodeFunctionData(functionFragment: 'escrowsCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'initialize', values: [AddressLike, AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'isEscrowContract', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'proxiableUUID', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'reputationRegistry', values?: undefined): string;
encodeFunctionData(functionFragment: 'reviewWindow', values?: undefined): string;
encodeFunctionData(functionFragment: 'setEscrowImplementation', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setReputationRegistry', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setReviewWindow', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setUSDCToken', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'upgradeToAndCall', values: [AddressLike, BytesLike]): string;

    decodeFunctionResult(functionFragment: 'UPGRADE_INTERFACE_VERSION', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'allEscrows', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'cUSDCToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createEscrow', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'escrowImplementation', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'escrowsCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'initialize', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isEscrowContract', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'proxiableUUID', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'reputationRegistry', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'reviewWindow', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setEscrowImplementation', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setReputationRegistry', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setReviewWindow', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setUSDCToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'upgradeToAndCall', data: BytesLike): Result;
  }

  
    export namespace EscrowCreatedEvent {
      export type InputTuple = [escrowAddress: AddressLike, client: AddressLike, freelancer: AddressLike, totalMilestones: BigNumberish];
      export type OutputTuple = [escrowAddress: string, client: string, freelancer: string, totalMilestones: bigint];
      export interface OutputObject {escrowAddress: string, client: string, freelancer: string, totalMilestones: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ImplementationUpdatedEvent {
      export type InputTuple = [oldImpl: AddressLike, newImpl: AddressLike];
      export type OutputTuple = [oldImpl: string, newImpl: string];
      export interface OutputObject {oldImpl: string, newImpl: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace InitializedEvent {
      export type InputTuple = [version: BigNumberish];
      export type OutputTuple = [version: bigint];
      export interface OutputObject {version: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ReputationRegistryUpdatedEvent {
      export type InputTuple = [oldRegistry: AddressLike, newRegistry: AddressLike];
      export type OutputTuple = [oldRegistry: string, newRegistry: string];
      export interface OutputObject {oldRegistry: string, newRegistry: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ReviewWindowUpdatedEvent {
      export type InputTuple = [oldWindow: BigNumberish, newWindow: BigNumberish];
      export type OutputTuple = [oldWindow: bigint, newWindow: bigint];
      export interface OutputObject {oldWindow: bigint, newWindow: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TokenUpdatedEvent {
      export type InputTuple = [oldToken: AddressLike, newToken: AddressLike];
      export type OutputTuple = [oldToken: string, newToken: string];
      export interface OutputObject {oldToken: string, newToken: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UpgradedEvent {
      export type InputTuple = [implementation: AddressLike];
      export type OutputTuple = [implementation: string];
      export interface OutputObject {implementation: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface NoxEscrowFactory extends BaseContract {
    
    connect(runner?: ContractRunner | null): NoxEscrowFactory;
    waitForDeployment(): Promise<this>;

    interface: NoxEscrowFactoryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    UPGRADE_INTERFACE_VERSION: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    allEscrows: TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >
    

    
    cUSDCToken: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    createEscrow: TypedContractMethod<
      [_freelancer: AddressLike, _teeArbiter: AddressLike, _totalMilestones: BigNumberish, _customReviewWindow: BigNumberish, ],
      [string],
      'nonpayable'
    >
    

    
    escrowImplementation: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    escrowsCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    initialize: TypedContractMethod<
      [_escrowImplementation: AddressLike, _reputationRegistry: AddressLike, _cUSDCToken: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    isEscrowContract: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    proxiableUUID: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    reputationRegistry: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    reviewWindow: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    setEscrowImplementation: TypedContractMethod<
      [_newImplementation: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setReputationRegistry: TypedContractMethod<
      [_newRegistry: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setReviewWindow: TypedContractMethod<
      [_newReviewWindow: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setUSDCToken: TypedContractMethod<
      [_newToken: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    upgradeToAndCall: TypedContractMethod<
      [newImplementation: AddressLike, data: BytesLike, ],
      [void],
      'payable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'UPGRADE_INTERFACE_VERSION'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'allEscrows'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'cUSDCToken'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'createEscrow'): TypedContractMethod<
      [_freelancer: AddressLike, _teeArbiter: AddressLike, _totalMilestones: BigNumberish, _customReviewWindow: BigNumberish, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'escrowImplementation'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'escrowsCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'initialize'): TypedContractMethod<
      [_escrowImplementation: AddressLike, _reputationRegistry: AddressLike, _cUSDCToken: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'isEscrowContract'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'proxiableUUID'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'reputationRegistry'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'reviewWindow'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'setEscrowImplementation'): TypedContractMethod<
      [_newImplementation: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setReputationRegistry'): TypedContractMethod<
      [_newRegistry: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setReviewWindow'): TypedContractMethod<
      [_newReviewWindow: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setUSDCToken'): TypedContractMethod<
      [_newToken: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'upgradeToAndCall'): TypedContractMethod<
      [newImplementation: AddressLike, data: BytesLike, ],
      [void],
      'payable'
    >;

    getEvent(key: 'EscrowCreated'): TypedContractEvent<EscrowCreatedEvent.InputTuple, EscrowCreatedEvent.OutputTuple, EscrowCreatedEvent.OutputObject>;
getEvent(key: 'ImplementationUpdated'): TypedContractEvent<ImplementationUpdatedEvent.InputTuple, ImplementationUpdatedEvent.OutputTuple, ImplementationUpdatedEvent.OutputObject>;
getEvent(key: 'Initialized'): TypedContractEvent<InitializedEvent.InputTuple, InitializedEvent.OutputTuple, InitializedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'ReputationRegistryUpdated'): TypedContractEvent<ReputationRegistryUpdatedEvent.InputTuple, ReputationRegistryUpdatedEvent.OutputTuple, ReputationRegistryUpdatedEvent.OutputObject>;
getEvent(key: 'ReviewWindowUpdated'): TypedContractEvent<ReviewWindowUpdatedEvent.InputTuple, ReviewWindowUpdatedEvent.OutputTuple, ReviewWindowUpdatedEvent.OutputObject>;
getEvent(key: 'TokenUpdated'): TypedContractEvent<TokenUpdatedEvent.InputTuple, TokenUpdatedEvent.OutputTuple, TokenUpdatedEvent.OutputObject>;
getEvent(key: 'Upgraded'): TypedContractEvent<UpgradedEvent.InputTuple, UpgradedEvent.OutputTuple, UpgradedEvent.OutputObject>;

    filters: {
      
      'EscrowCreated(address,address,address,uint256)': TypedContractEvent<EscrowCreatedEvent.InputTuple, EscrowCreatedEvent.OutputTuple, EscrowCreatedEvent.OutputObject>;
      EscrowCreated: TypedContractEvent<EscrowCreatedEvent.InputTuple, EscrowCreatedEvent.OutputTuple, EscrowCreatedEvent.OutputObject>;
    

      'ImplementationUpdated(address,address)': TypedContractEvent<ImplementationUpdatedEvent.InputTuple, ImplementationUpdatedEvent.OutputTuple, ImplementationUpdatedEvent.OutputObject>;
      ImplementationUpdated: TypedContractEvent<ImplementationUpdatedEvent.InputTuple, ImplementationUpdatedEvent.OutputTuple, ImplementationUpdatedEvent.OutputObject>;
    

      'Initialized(uint64)': TypedContractEvent<InitializedEvent.InputTuple, InitializedEvent.OutputTuple, InitializedEvent.OutputObject>;
      Initialized: TypedContractEvent<InitializedEvent.InputTuple, InitializedEvent.OutputTuple, InitializedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'ReputationRegistryUpdated(address,address)': TypedContractEvent<ReputationRegistryUpdatedEvent.InputTuple, ReputationRegistryUpdatedEvent.OutputTuple, ReputationRegistryUpdatedEvent.OutputObject>;
      ReputationRegistryUpdated: TypedContractEvent<ReputationRegistryUpdatedEvent.InputTuple, ReputationRegistryUpdatedEvent.OutputTuple, ReputationRegistryUpdatedEvent.OutputObject>;
    

      'ReviewWindowUpdated(uint256,uint256)': TypedContractEvent<ReviewWindowUpdatedEvent.InputTuple, ReviewWindowUpdatedEvent.OutputTuple, ReviewWindowUpdatedEvent.OutputObject>;
      ReviewWindowUpdated: TypedContractEvent<ReviewWindowUpdatedEvent.InputTuple, ReviewWindowUpdatedEvent.OutputTuple, ReviewWindowUpdatedEvent.OutputObject>;
    

      'TokenUpdated(address,address)': TypedContractEvent<TokenUpdatedEvent.InputTuple, TokenUpdatedEvent.OutputTuple, TokenUpdatedEvent.OutputObject>;
      TokenUpdated: TypedContractEvent<TokenUpdatedEvent.InputTuple, TokenUpdatedEvent.OutputTuple, TokenUpdatedEvent.OutputObject>;
    

      'Upgraded(address)': TypedContractEvent<UpgradedEvent.InputTuple, UpgradedEvent.OutputTuple, UpgradedEvent.OutputObject>;
      Upgraded: TypedContractEvent<UpgradedEvent.InputTuple, UpgradedEvent.OutputTuple, UpgradedEvent.OutputObject>;
    
    };
  }