/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface NoxEscrowFactoryInterface extends Interface {
    getFunction(nameOrSignature: "UPGRADE_INTERFACE_VERSION" | "allEscrows" | "cUSDCToken" | "canonicalTeeArbiter" | "createEscrow" | "escrowImplementation" | "escrowsCount" | "initialize" | "isEscrowContract" | "mutualCancelWindow" | "owner" | "platformFeeBps" | "proxiableUUID" | "renounceOwnership" | "reputationRegistry" | "reviewWindow" | "setCanonicalTeeArbiter" | "setEscrowImplementation" | "setMutualCancelWindow" | "setPlatformFeeBps" | "setReputationRegistry" | "setReviewWindow" | "setTreasury" | "setUSDCToken" | "transferOwnership" | "treasury" | "upgradeToAndCall"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "CanonicalArbiterUpdated" | "EscrowCreated" | "ImplementationUpdated" | "Initialized" | "MutualCancelWindowUpdated" | "OwnershipTransferred" | "PlatformFeeUpdated" | "ReputationRegistryUpdated" | "ReviewWindowUpdated" | "TokenUpdated" | "TreasuryUpdated" | "Upgraded"): EventFragment;

    encodeFunctionData(functionFragment: 'UPGRADE_INTERFACE_VERSION', values?: undefined): string;
encodeFunctionData(functionFragment: 'allEscrows', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'cUSDCToken', values?: undefined): string;
encodeFunctionData(functionFragment: 'canonicalTeeArbiter', values?: undefined): string;
encodeFunctionData(functionFragment: 'createEscrow', values: [AddressLike, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'escrowImplementation', values?: undefined): string;
encodeFunctionData(functionFragment: 'escrowsCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'initialize', values: [AddressLike, AddressLike, AddressLike, AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'isEscrowContract', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'mutualCancelWindow', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'platformFeeBps', values?: undefined): string;
encodeFunctionData(functionFragment: 'proxiableUUID', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'reputationRegistry', values?: undefined): string;
encodeFunctionData(functionFragment: 'reviewWindow', values?: undefined): string;
encodeFunctionData(functionFragment: 'setCanonicalTeeArbiter', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setEscrowImplementation', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setMutualCancelWindow', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setPlatformFeeBps', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setReputationRegistry', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setReviewWindow', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setTreasury', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setUSDCToken', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'treasury', values?: undefined): string;
encodeFunctionData(functionFragment: 'upgradeToAndCall', values: [AddressLike, BytesLike]): string;

    decodeFunctionResult(functionFragment: 'UPGRADE_INTERFACE_VERSION', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'allEscrows', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'cUSDCToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'canonicalTeeArbiter', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createEscrow', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'escrowImplementation', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'escrowsCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'initialize', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isEscrowContract', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'mutualCancelWindow', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'platformFeeBps', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'proxiableUUID', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'reputationRegistry', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'reviewWindow', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setCanonicalTeeArbiter', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setEscrowImplementation', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setMutualCancelWindow', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setPlatformFeeBps', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setReputationRegistry', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setReviewWindow', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setTreasury', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setUSDCToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'treasury', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'upgradeToAndCall', data: BytesLike): Result;
  }

  
    export namespace CanonicalArbiterUpdatedEvent {
      export type InputTuple = [oldArbiter: AddressLike, newArbiter: AddressLike];
      export type OutputTuple = [oldArbiter: string, newArbiter: string];
      export interface OutputObject {oldArbiter: string, newArbiter: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace EscrowCreatedEvent {
      export type InputTuple = [escrowAddress: AddressLike, client: AddressLike, freelancer: AddressLike, totalMilestones: BigNumberish];
      export type OutputTuple = [escrowAddress: string, client: string, freelancer: string, totalMilestones: bigint];
      export interface OutputObject {escrowAddress: string, client: string, freelancer: string, totalMilestones: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ImplementationUpdatedEvent {
      export type InputTuple = [oldImpl: AddressLike, newImpl: AddressLike];
      export type OutputTuple = [oldImpl: string, newImpl: string];
      export interface OutputObject {oldImpl: string, newImpl: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace InitializedEvent {
      export type InputTuple = [version: BigNumberish];
      export type OutputTuple = [version: bigint];
      export interface OutputObject {version: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MutualCancelWindowUpdatedEvent {
      export type InputTuple = [oldWindow: BigNumberish, newWindow: BigNumberish];
      export type OutputTuple = [oldWindow: bigint, newWindow: bigint];
      export interface OutputObject {oldWindow: bigint, newWindow: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PlatformFeeUpdatedEvent {
      export type InputTuple = [oldFeeBps: BigNumberish, newFeeBps: BigNumberish];
      export type OutputTuple = [oldFeeBps: bigint, newFeeBps: bigint];
      export interface OutputObject {oldFeeBps: bigint, newFeeBps: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ReputationRegistryUpdatedEvent {
      export type InputTuple = [oldRegistry: AddressLike, newRegistry: AddressLike];
      export type OutputTuple = [oldRegistry: string, newRegistry: string];
      export interface OutputObject {oldRegistry: string, newRegistry: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ReviewWindowUpdatedEvent {
      export type InputTuple = [oldWindow: BigNumberish, newWindow: BigNumberish];
      export type OutputTuple = [oldWindow: bigint, newWindow: bigint];
      export interface OutputObject {oldWindow: bigint, newWindow: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TokenUpdatedEvent {
      export type InputTuple = [oldToken: AddressLike, newToken: AddressLike];
      export type OutputTuple = [oldToken: string, newToken: string];
      export interface OutputObject {oldToken: string, newToken: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TreasuryUpdatedEvent {
      export type InputTuple = [oldTreasury: AddressLike, newTreasury: AddressLike];
      export type OutputTuple = [oldTreasury: string, newTreasury: string];
      export interface OutputObject {oldTreasury: string, newTreasury: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UpgradedEvent {
      export type InputTuple = [implementation: AddressLike];
      export type OutputTuple = [implementation: string];
      export interface OutputObject {implementation: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface NoxEscrowFactory extends BaseContract {
    
    connect(runner?: ContractRunner | null): NoxEscrowFactory;
    waitForDeployment(): Promise<this>;

    interface: NoxEscrowFactoryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    UPGRADE_INTERFACE_VERSION: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    allEscrows: TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >
    

    
    cUSDCToken: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    canonicalTeeArbiter: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    createEscrow: TypedContractMethod<
      [_freelancer: AddressLike, _totalMilestones: BigNumberish, _customReviewWindow: BigNumberish, ],
      [string],
      'nonpayable'
    >
    

    
    escrowImplementation: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    escrowsCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    initialize: TypedContractMethod<
      [_escrowImplementation: AddressLike, _reputationRegistry: AddressLike, _cUSDCToken: AddressLike, _canonicalTeeArbiter: AddressLike, _treasury: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    isEscrowContract: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    mutualCancelWindow: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    platformFeeBps: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    proxiableUUID: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    reputationRegistry: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    reviewWindow: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    setCanonicalTeeArbiter: TypedContractMethod<
      [_newArbiter: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setEscrowImplementation: TypedContractMethod<
      [_newImplementation: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setMutualCancelWindow: TypedContractMethod<
      [_newMutualCancelWindow: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setPlatformFeeBps: TypedContractMethod<
      [_newFeeBps: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setReputationRegistry: TypedContractMethod<
      [_newRegistry: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setReviewWindow: TypedContractMethod<
      [_newReviewWindow: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setTreasury: TypedContractMethod<
      [_newTreasury: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setUSDCToken: TypedContractMethod<
      [_newToken: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    treasury: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    upgradeToAndCall: TypedContractMethod<
      [newImplementation: AddressLike, data: BytesLike, ],
      [void],
      'payable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'UPGRADE_INTERFACE_VERSION'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'allEscrows'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'cUSDCToken'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'canonicalTeeArbiter'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'createEscrow'): TypedContractMethod<
      [_freelancer: AddressLike, _totalMilestones: BigNumberish, _customReviewWindow: BigNumberish, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'escrowImplementation'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'escrowsCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'initialize'): TypedContractMethod<
      [_escrowImplementation: AddressLike, _reputationRegistry: AddressLike, _cUSDCToken: AddressLike, _canonicalTeeArbiter: AddressLike, _treasury: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'isEscrowContract'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'mutualCancelWindow'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'platformFeeBps'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'proxiableUUID'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'reputationRegistry'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'reviewWindow'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'setCanonicalTeeArbiter'): TypedContractMethod<
      [_newArbiter: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setEscrowImplementation'): TypedContractMethod<
      [_newImplementation: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setMutualCancelWindow'): TypedContractMethod<
      [_newMutualCancelWindow: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setPlatformFeeBps'): TypedContractMethod<
      [_newFeeBps: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setReputationRegistry'): TypedContractMethod<
      [_newRegistry: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setReviewWindow'): TypedContractMethod<
      [_newReviewWindow: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setTreasury'): TypedContractMethod<
      [_newTreasury: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setUSDCToken'): TypedContractMethod<
      [_newToken: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'treasury'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'upgradeToAndCall'): TypedContractMethod<
      [newImplementation: AddressLike, data: BytesLike, ],
      [void],
      'payable'
    >;

    getEvent(key: 'CanonicalArbiterUpdated'): TypedContractEvent<CanonicalArbiterUpdatedEvent.InputTuple, CanonicalArbiterUpdatedEvent.OutputTuple, CanonicalArbiterUpdatedEvent.OutputObject>;
getEvent(key: 'EscrowCreated'): TypedContractEvent<EscrowCreatedEvent.InputTuple, EscrowCreatedEvent.OutputTuple, EscrowCreatedEvent.OutputObject>;
getEvent(key: 'ImplementationUpdated'): TypedContractEvent<ImplementationUpdatedEvent.InputTuple, ImplementationUpdatedEvent.OutputTuple, ImplementationUpdatedEvent.OutputObject>;
getEvent(key: 'Initialized'): TypedContractEvent<InitializedEvent.InputTuple, InitializedEvent.OutputTuple, InitializedEvent.OutputObject>;
getEvent(key: 'MutualCancelWindowUpdated'): TypedContractEvent<MutualCancelWindowUpdatedEvent.InputTuple, MutualCancelWindowUpdatedEvent.OutputTuple, MutualCancelWindowUpdatedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'PlatformFeeUpdated'): TypedContractEvent<PlatformFeeUpdatedEvent.InputTuple, PlatformFeeUpdatedEvent.OutputTuple, PlatformFeeUpdatedEvent.OutputObject>;
getEvent(key: 'ReputationRegistryUpdated'): TypedContractEvent<ReputationRegistryUpdatedEvent.InputTuple, ReputationRegistryUpdatedEvent.OutputTuple, ReputationRegistryUpdatedEvent.OutputObject>;
getEvent(key: 'ReviewWindowUpdated'): TypedContractEvent<ReviewWindowUpdatedEvent.InputTuple, ReviewWindowUpdatedEvent.OutputTuple, ReviewWindowUpdatedEvent.OutputObject>;
getEvent(key: 'TokenUpdated'): TypedContractEvent<TokenUpdatedEvent.InputTuple, TokenUpdatedEvent.OutputTuple, TokenUpdatedEvent.OutputObject>;
getEvent(key: 'TreasuryUpdated'): TypedContractEvent<TreasuryUpdatedEvent.InputTuple, TreasuryUpdatedEvent.OutputTuple, TreasuryUpdatedEvent.OutputObject>;
getEvent(key: 'Upgraded'): TypedContractEvent<UpgradedEvent.InputTuple, UpgradedEvent.OutputTuple, UpgradedEvent.OutputObject>;

    filters: {
      
      'CanonicalArbiterUpdated(address,address)': TypedContractEvent<CanonicalArbiterUpdatedEvent.InputTuple, CanonicalArbiterUpdatedEvent.OutputTuple, CanonicalArbiterUpdatedEvent.OutputObject>;
      CanonicalArbiterUpdated: TypedContractEvent<CanonicalArbiterUpdatedEvent.InputTuple, CanonicalArbiterUpdatedEvent.OutputTuple, CanonicalArbiterUpdatedEvent.OutputObject>;
    

      'EscrowCreated(address,address,address,uint256)': TypedContractEvent<EscrowCreatedEvent.InputTuple, EscrowCreatedEvent.OutputTuple, EscrowCreatedEvent.OutputObject>;
      EscrowCreated: TypedContractEvent<EscrowCreatedEvent.InputTuple, EscrowCreatedEvent.OutputTuple, EscrowCreatedEvent.OutputObject>;
    

      'ImplementationUpdated(address,address)': TypedContractEvent<ImplementationUpdatedEvent.InputTuple, ImplementationUpdatedEvent.OutputTuple, ImplementationUpdatedEvent.OutputObject>;
      ImplementationUpdated: TypedContractEvent<ImplementationUpdatedEvent.InputTuple, ImplementationUpdatedEvent.OutputTuple, ImplementationUpdatedEvent.OutputObject>;
    

      'Initialized(uint64)': TypedContractEvent<InitializedEvent.InputTuple, InitializedEvent.OutputTuple, InitializedEvent.OutputObject>;
      Initialized: TypedContractEvent<InitializedEvent.InputTuple, InitializedEvent.OutputTuple, InitializedEvent.OutputObject>;
    

      'MutualCancelWindowUpdated(uint256,uint256)': TypedContractEvent<MutualCancelWindowUpdatedEvent.InputTuple, MutualCancelWindowUpdatedEvent.OutputTuple, MutualCancelWindowUpdatedEvent.OutputObject>;
      MutualCancelWindowUpdated: TypedContractEvent<MutualCancelWindowUpdatedEvent.InputTuple, MutualCancelWindowUpdatedEvent.OutputTuple, MutualCancelWindowUpdatedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'PlatformFeeUpdated(uint256,uint256)': TypedContractEvent<PlatformFeeUpdatedEvent.InputTuple, PlatformFeeUpdatedEvent.OutputTuple, PlatformFeeUpdatedEvent.OutputObject>;
      PlatformFeeUpdated: TypedContractEvent<PlatformFeeUpdatedEvent.InputTuple, PlatformFeeUpdatedEvent.OutputTuple, PlatformFeeUpdatedEvent.OutputObject>;
    

      'ReputationRegistryUpdated(address,address)': TypedContractEvent<ReputationRegistryUpdatedEvent.InputTuple, ReputationRegistryUpdatedEvent.OutputTuple, ReputationRegistryUpdatedEvent.OutputObject>;
      ReputationRegistryUpdated: TypedContractEvent<ReputationRegistryUpdatedEvent.InputTuple, ReputationRegistryUpdatedEvent.OutputTuple, ReputationRegistryUpdatedEvent.OutputObject>;
    

      'ReviewWindowUpdated(uint256,uint256)': TypedContractEvent<ReviewWindowUpdatedEvent.InputTuple, ReviewWindowUpdatedEvent.OutputTuple, ReviewWindowUpdatedEvent.OutputObject>;
      ReviewWindowUpdated: TypedContractEvent<ReviewWindowUpdatedEvent.InputTuple, ReviewWindowUpdatedEvent.OutputTuple, ReviewWindowUpdatedEvent.OutputObject>;
    

      'TokenUpdated(address,address)': TypedContractEvent<TokenUpdatedEvent.InputTuple, TokenUpdatedEvent.OutputTuple, TokenUpdatedEvent.OutputObject>;
      TokenUpdated: TypedContractEvent<TokenUpdatedEvent.InputTuple, TokenUpdatedEvent.OutputTuple, TokenUpdatedEvent.OutputObject>;
    

      'TreasuryUpdated(address,address)': TypedContractEvent<TreasuryUpdatedEvent.InputTuple, TreasuryUpdatedEvent.OutputTuple, TreasuryUpdatedEvent.OutputObject>;
      TreasuryUpdated: TypedContractEvent<TreasuryUpdatedEvent.InputTuple, TreasuryUpdatedEvent.OutputTuple, TreasuryUpdatedEvent.OutputObject>;
    

      'Upgraded(address)': TypedContractEvent<UpgradedEvent.InputTuple, UpgradedEvent.OutputTuple, UpgradedEvent.OutputObject>;
      Upgraded: TypedContractEvent<UpgradedEvent.InputTuple, UpgradedEvent.OutputTuple, UpgradedEvent.OutputObject>;
    
    };
  }