/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { INoxEscrowContract, INoxEscrowContractInterface } from "../../interfaces/INoxEscrowContract.js";

  const _abi = [
  {
    "inputs": [],
    "name": "AlreadySettled",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "AlreadySubmitted",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidArbiter",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidClient",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidFreelancer",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidMilestonesCount",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidRating",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidReputationRegistry",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidState",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidToken",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "LengthMismatch",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "MutualCancellationNotRequested",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "ReviewWindowExpired",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "ReviewWindowNotExpired",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "Unauthorized",
    "type": "error"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "client",
        "type": "address"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "freelancer",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "totalMilestones",
        "type": "uint256"
      }
    ],
    "name": "ContractInitialized",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "milestoneIndex",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "euint256",
        "name": "deliverableHash",
        "type": "bytes32"
      }
    ],
    "name": "DeliverableSubmitted",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "milestoneIndex",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "euint256",
        "name": "requirementsHash",
        "type": "bytes32"
      },
      {
        "indexed": false,
        "internalType": "euint256",
        "name": "deliverableHash",
        "type": "bytes32"
      }
    ],
    "name": "DisputeOpened",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "milestoneIndex",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "bool",
        "name": "ruledInFavorOfFreelancer",
        "type": "bool"
      }
    ],
    "name": "DisputeResolved",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "milestoneIndex",
        "type": "uint256"
      }
    ],
    "name": "MilestoneApproved",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [],
    "name": "MutualCancellationExecuted",
    "type": "event"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "_client",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "_freelancer",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "_teeArbiter",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "_cUSDC",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "_reputationRegistry",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "_totalMilestones",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "_reviewWindow",
        "type": "uint256"
      }
    ],
    "name": "initialize",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "externalEuint256[]",
        "name": "milestonePayouts",
        "type": "bytes32[]"
      },
      {
        "internalType": "bytes[]",
        "name": "payoutProofs",
        "type": "bytes[]"
      },
      {
        "internalType": "externalEuint256[]",
        "name": "milestoneReqs",
        "type": "bytes32[]"
      },
      {
        "internalType": "bytes[]",
        "name": "reqsProofs",
        "type": "bytes[]"
      }
    ],
    "name": "initializeEscrow",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "mutualCancel",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "raiseDispute",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "rating",
        "type": "uint256"
      }
    ],
    "name": "releaseMilestone",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bool",
        "name": "ruleInFavorOfFreelancer",
        "type": "bool"
      }
    ],
    "name": "resolveDispute",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "externalEuint256",
        "name": "_deliverableHash",
        "type": "bytes32"
      },
      {
        "internalType": "bytes",
        "name": "proof",
        "type": "bytes"
      }
    ],
    "name": "submitDeliverable",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  export class INoxEscrowContract__factory {
    static readonly abi = _abi;
    static createInterface(): INoxEscrowContractInterface {
      return new Interface(_abi) as INoxEscrowContractInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): INoxEscrowContract {
      return new Contract(address, _abi, runner) as unknown as INoxEscrowContract;
    }
  }
  