/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { INoxEscrowFactory, INoxEscrowFactoryInterface } from "../../NoxEscrowReputation.sol/INoxEscrowFactory.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "_contract",
        "type": "address"
      }
    ],
    "name": "isEscrowContract",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  export class INoxEscrowFactory__factory {
    static readonly abi = _abi;
    static createInterface(): INoxEscrowFactoryInterface {
      return new Interface(_abi) as INoxEscrowFactoryInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): INoxEscrowFactory {
      return new Contract(address, _abi, runner) as unknown as INoxEscrowFactory;
    }
  }
  