/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface INoxEscrowContractInterface extends Interface {
    getFunction(nameOrSignature: "initialize" | "initializeEscrow" | "mutualCancel" | "raiseDispute" | "releaseMilestone" | "resolveDispute" | "submitDeliverable"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "ContractInitialized" | "DeliverableSubmitted" | "DisputeOpened" | "DisputeResolved" | "MilestoneApproved" | "MutualCancellationExecuted"): EventFragment;

    encodeFunctionData(functionFragment: 'initialize', values: [AddressLike, AddressLike, AddressLike, AddressLike, AddressLike, BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'initializeEscrow', values: [BytesLike[], BytesLike[], BytesLike[], BytesLike[]]): string;
encodeFunctionData(functionFragment: 'mutualCancel', values?: undefined): string;
encodeFunctionData(functionFragment: 'raiseDispute', values?: undefined): string;
encodeFunctionData(functionFragment: 'releaseMilestone', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'resolveDispute', values: [boolean]): string;
encodeFunctionData(functionFragment: 'submitDeliverable', values: [BytesLike, BytesLike]): string;

    decodeFunctionResult(functionFragment: 'initialize', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'initializeEscrow', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'mutualCancel', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'raiseDispute', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'releaseMilestone', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'resolveDispute', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'submitDeliverable', data: BytesLike): Result;
  }

  
    export namespace ContractInitializedEvent {
      export type InputTuple = [client: AddressLike, freelancer: AddressLike, totalMilestones: BigNumberish];
      export type OutputTuple = [client: string, freelancer: string, totalMilestones: bigint];
      export interface OutputObject {client: string, freelancer: string, totalMilestones: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DeliverableSubmittedEvent {
      export type InputTuple = [milestoneIndex: BigNumberish, deliverableHash: BytesLike];
      export type OutputTuple = [milestoneIndex: bigint, deliverableHash: string];
      export interface OutputObject {milestoneIndex: bigint, deliverableHash: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DisputeOpenedEvent {
      export type InputTuple = [milestoneIndex: BigNumberish, requirementsHash: BytesLike, deliverableHash: BytesLike];
      export type OutputTuple = [milestoneIndex: bigint, requirementsHash: string, deliverableHash: string];
      export interface OutputObject {milestoneIndex: bigint, requirementsHash: string, deliverableHash: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DisputeResolvedEvent {
      export type InputTuple = [milestoneIndex: BigNumberish, ruledInFavorOfFreelancer: boolean];
      export type OutputTuple = [milestoneIndex: bigint, ruledInFavorOfFreelancer: boolean];
      export interface OutputObject {milestoneIndex: bigint, ruledInFavorOfFreelancer: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MilestoneApprovedEvent {
      export type InputTuple = [milestoneIndex: BigNumberish];
      export type OutputTuple = [milestoneIndex: bigint];
      export interface OutputObject {milestoneIndex: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MutualCancellationExecutedEvent {
      export type InputTuple = [];
      export type OutputTuple = [];
      export interface OutputObject {};
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface INoxEscrowContract extends BaseContract {
    
    connect(runner?: ContractRunner | null): INoxEscrowContract;
    waitForDeployment(): Promise<this>;

    interface: INoxEscrowContractInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    initialize: TypedContractMethod<
      [_client: AddressLike, _freelancer: AddressLike, _teeArbiter: AddressLike, _cUSDC: AddressLike, _reputationRegistry: AddressLike, _totalMilestones: BigNumberish, _reviewWindow: BigNumberish, _mutualCancelWindow: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    initializeEscrow: TypedContractMethod<
      [milestonePayouts: BytesLike[], payoutProofs: BytesLike[], milestoneReqs: BytesLike[], reqsProofs: BytesLike[], ],
      [void],
      'nonpayable'
    >
    

    
    mutualCancel: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    raiseDispute: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    releaseMilestone: TypedContractMethod<
      [rating: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    resolveDispute: TypedContractMethod<
      [ruleInFavorOfFreelancer: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    submitDeliverable: TypedContractMethod<
      [_deliverableHash: BytesLike, proof: BytesLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'initialize'): TypedContractMethod<
      [_client: AddressLike, _freelancer: AddressLike, _teeArbiter: AddressLike, _cUSDC: AddressLike, _reputationRegistry: AddressLike, _totalMilestones: BigNumberish, _reviewWindow: BigNumberish, _mutualCancelWindow: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'initializeEscrow'): TypedContractMethod<
      [milestonePayouts: BytesLike[], payoutProofs: BytesLike[], milestoneReqs: BytesLike[], reqsProofs: BytesLike[], ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'mutualCancel'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'raiseDispute'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'releaseMilestone'): TypedContractMethod<
      [rating: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'resolveDispute'): TypedContractMethod<
      [ruleInFavorOfFreelancer: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'submitDeliverable'): TypedContractMethod<
      [_deliverableHash: BytesLike, proof: BytesLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'ContractInitialized'): TypedContractEvent<ContractInitializedEvent.InputTuple, ContractInitializedEvent.OutputTuple, ContractInitializedEvent.OutputObject>;
getEvent(key: 'DeliverableSubmitted'): TypedContractEvent<DeliverableSubmittedEvent.InputTuple, DeliverableSubmittedEvent.OutputTuple, DeliverableSubmittedEvent.OutputObject>;
getEvent(key: 'DisputeOpened'): TypedContractEvent<DisputeOpenedEvent.InputTuple, DisputeOpenedEvent.OutputTuple, DisputeOpenedEvent.OutputObject>;
getEvent(key: 'DisputeResolved'): TypedContractEvent<DisputeResolvedEvent.InputTuple, DisputeResolvedEvent.OutputTuple, DisputeResolvedEvent.OutputObject>;
getEvent(key: 'MilestoneApproved'): TypedContractEvent<MilestoneApprovedEvent.InputTuple, MilestoneApprovedEvent.OutputTuple, MilestoneApprovedEvent.OutputObject>;
getEvent(key: 'MutualCancellationExecuted'): TypedContractEvent<MutualCancellationExecutedEvent.InputTuple, MutualCancellationExecutedEvent.OutputTuple, MutualCancellationExecutedEvent.OutputObject>;

    filters: {
      
      'ContractInitialized(address,address,uint256)': TypedContractEvent<ContractInitializedEvent.InputTuple, ContractInitializedEvent.OutputTuple, ContractInitializedEvent.OutputObject>;
      ContractInitialized: TypedContractEvent<ContractInitializedEvent.InputTuple, ContractInitializedEvent.OutputTuple, ContractInitializedEvent.OutputObject>;
    

      'DeliverableSubmitted(uint256,bytes32)': TypedContractEvent<DeliverableSubmittedEvent.InputTuple, DeliverableSubmittedEvent.OutputTuple, DeliverableSubmittedEvent.OutputObject>;
      DeliverableSubmitted: TypedContractEvent<DeliverableSubmittedEvent.InputTuple, DeliverableSubmittedEvent.OutputTuple, DeliverableSubmittedEvent.OutputObject>;
    

      'DisputeOpened(uint256,bytes32,bytes32)': TypedContractEvent<DisputeOpenedEvent.InputTuple, DisputeOpenedEvent.OutputTuple, DisputeOpenedEvent.OutputObject>;
      DisputeOpened: TypedContractEvent<DisputeOpenedEvent.InputTuple, DisputeOpenedEvent.OutputTuple, DisputeOpenedEvent.OutputObject>;
    

      'DisputeResolved(uint256,bool)': TypedContractEvent<DisputeResolvedEvent.InputTuple, DisputeResolvedEvent.OutputTuple, DisputeResolvedEvent.OutputObject>;
      DisputeResolved: TypedContractEvent<DisputeResolvedEvent.InputTuple, DisputeResolvedEvent.OutputTuple, DisputeResolvedEvent.OutputObject>;
    

      'MilestoneApproved(uint256)': TypedContractEvent<MilestoneApprovedEvent.InputTuple, MilestoneApprovedEvent.OutputTuple, MilestoneApprovedEvent.OutputObject>;
      MilestoneApproved: TypedContractEvent<MilestoneApprovedEvent.InputTuple, MilestoneApprovedEvent.OutputTuple, MilestoneApprovedEvent.OutputObject>;
    

      'MutualCancellationExecuted()': TypedContractEvent<MutualCancellationExecutedEvent.InputTuple, MutualCancellationExecutedEvent.OutputTuple, MutualCancellationExecutedEvent.OutputObject>;
      MutualCancellationExecuted: TypedContractEvent<MutualCancellationExecutedEvent.InputTuple, MutualCancellationExecutedEvent.OutputTuple, MutualCancellationExecutedEvent.OutputObject>;
    
    };
  }