/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface INoxEscrowFactoryInterface extends Interface {
    getFunction(nameOrSignature: "allEscrows" | "createEscrow" | "escrowsCount" | "initialize" | "isEscrowContract" | "setEscrowImplementation" | "setReputationRegistry" | "setReviewWindow" | "setUSDCToken"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "EscrowCreated" | "ImplementationUpdated" | "ReputationRegistryUpdated" | "ReviewWindowUpdated" | "TokenUpdated"): EventFragment;

    encodeFunctionData(functionFragment: 'allEscrows', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'createEscrow', values: [AddressLike, AddressLike, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'escrowsCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'initialize', values: [AddressLike, AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'isEscrowContract', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setEscrowImplementation', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setReputationRegistry', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setReviewWindow', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setUSDCToken', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'allEscrows', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createEscrow', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'escrowsCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'initialize', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isEscrowContract', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setEscrowImplementation', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setReputationRegistry', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setReviewWindow', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setUSDCToken', data: BytesLike): Result;
  }

  
    export namespace EscrowCreatedEvent {
      export type InputTuple = [escrowAddress: AddressLike, client: AddressLike, freelancer: AddressLike, totalMilestones: BigNumberish];
      export type OutputTuple = [escrowAddress: string, client: string, freelancer: string, totalMilestones: bigint];
      export interface OutputObject {escrowAddress: string, client: string, freelancer: string, totalMilestones: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ImplementationUpdatedEvent {
      export type InputTuple = [oldImpl: AddressLike, newImpl: AddressLike];
      export type OutputTuple = [oldImpl: string, newImpl: string];
      export interface OutputObject {oldImpl: string, newImpl: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ReputationRegistryUpdatedEvent {
      export type InputTuple = [oldRegistry: AddressLike, newRegistry: AddressLike];
      export type OutputTuple = [oldRegistry: string, newRegistry: string];
      export interface OutputObject {oldRegistry: string, newRegistry: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ReviewWindowUpdatedEvent {
      export type InputTuple = [oldWindow: BigNumberish, newWindow: BigNumberish];
      export type OutputTuple = [oldWindow: bigint, newWindow: bigint];
      export interface OutputObject {oldWindow: bigint, newWindow: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TokenUpdatedEvent {
      export type InputTuple = [oldToken: AddressLike, newToken: AddressLike];
      export type OutputTuple = [oldToken: string, newToken: string];
      export interface OutputObject {oldToken: string, newToken: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface INoxEscrowFactory extends BaseContract {
    
    connect(runner?: ContractRunner | null): INoxEscrowFactory;
    waitForDeployment(): Promise<this>;

    interface: INoxEscrowFactoryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    allEscrows: TypedContractMethod<
      [index: BigNumberish, ],
      [string],
      'view'
    >
    

    
    createEscrow: TypedContractMethod<
      [_freelancer: AddressLike, _teeArbiter: AddressLike, _totalMilestones: BigNumberish, _customReviewWindow: BigNumberish, ],
      [string],
      'nonpayable'
    >
    

    
    escrowsCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    initialize: TypedContractMethod<
      [_escrowImplementation: AddressLike, _reputationRegistry: AddressLike, _cUSDCToken: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    isEscrowContract: TypedContractMethod<
      [_contract: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    setEscrowImplementation: TypedContractMethod<
      [_newImplementation: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setReputationRegistry: TypedContractMethod<
      [_newRegistry: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setReviewWindow: TypedContractMethod<
      [_newReviewWindow: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setUSDCToken: TypedContractMethod<
      [_newToken: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'allEscrows'): TypedContractMethod<
      [index: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'createEscrow'): TypedContractMethod<
      [_freelancer: AddressLike, _teeArbiter: AddressLike, _totalMilestones: BigNumberish, _customReviewWindow: BigNumberish, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'escrowsCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'initialize'): TypedContractMethod<
      [_escrowImplementation: AddressLike, _reputationRegistry: AddressLike, _cUSDCToken: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'isEscrowContract'): TypedContractMethod<
      [_contract: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'setEscrowImplementation'): TypedContractMethod<
      [_newImplementation: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setReputationRegistry'): TypedContractMethod<
      [_newRegistry: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setReviewWindow'): TypedContractMethod<
      [_newReviewWindow: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setUSDCToken'): TypedContractMethod<
      [_newToken: AddressLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'EscrowCreated'): TypedContractEvent<EscrowCreatedEvent.InputTuple, EscrowCreatedEvent.OutputTuple, EscrowCreatedEvent.OutputObject>;
getEvent(key: 'ImplementationUpdated'): TypedContractEvent<ImplementationUpdatedEvent.InputTuple, ImplementationUpdatedEvent.OutputTuple, ImplementationUpdatedEvent.OutputObject>;
getEvent(key: 'ReputationRegistryUpdated'): TypedContractEvent<ReputationRegistryUpdatedEvent.InputTuple, ReputationRegistryUpdatedEvent.OutputTuple, ReputationRegistryUpdatedEvent.OutputObject>;
getEvent(key: 'ReviewWindowUpdated'): TypedContractEvent<ReviewWindowUpdatedEvent.InputTuple, ReviewWindowUpdatedEvent.OutputTuple, ReviewWindowUpdatedEvent.OutputObject>;
getEvent(key: 'TokenUpdated'): TypedContractEvent<TokenUpdatedEvent.InputTuple, TokenUpdatedEvent.OutputTuple, TokenUpdatedEvent.OutputObject>;

    filters: {
      
      'EscrowCreated(address,address,address,uint256)': TypedContractEvent<EscrowCreatedEvent.InputTuple, EscrowCreatedEvent.OutputTuple, EscrowCreatedEvent.OutputObject>;
      EscrowCreated: TypedContractEvent<EscrowCreatedEvent.InputTuple, EscrowCreatedEvent.OutputTuple, EscrowCreatedEvent.OutputObject>;
    

      'ImplementationUpdated(address,address)': TypedContractEvent<ImplementationUpdatedEvent.InputTuple, ImplementationUpdatedEvent.OutputTuple, ImplementationUpdatedEvent.OutputObject>;
      ImplementationUpdated: TypedContractEvent<ImplementationUpdatedEvent.InputTuple, ImplementationUpdatedEvent.OutputTuple, ImplementationUpdatedEvent.OutputObject>;
    

      'ReputationRegistryUpdated(address,address)': TypedContractEvent<ReputationRegistryUpdatedEvent.InputTuple, ReputationRegistryUpdatedEvent.OutputTuple, ReputationRegistryUpdatedEvent.OutputObject>;
      ReputationRegistryUpdated: TypedContractEvent<ReputationRegistryUpdatedEvent.InputTuple, ReputationRegistryUpdatedEvent.OutputTuple, ReputationRegistryUpdatedEvent.OutputObject>;
    

      'ReviewWindowUpdated(uint256,uint256)': TypedContractEvent<ReviewWindowUpdatedEvent.InputTuple, ReviewWindowUpdatedEvent.OutputTuple, ReviewWindowUpdatedEvent.OutputObject>;
      ReviewWindowUpdated: TypedContractEvent<ReviewWindowUpdatedEvent.InputTuple, ReviewWindowUpdatedEvent.OutputTuple, ReviewWindowUpdatedEvent.OutputObject>;
    

      'TokenUpdated(address,address)': TypedContractEvent<TokenUpdatedEvent.InputTuple, TokenUpdatedEvent.OutputTuple, TokenUpdatedEvent.OutputObject>;
      TokenUpdated: TypedContractEvent<TokenUpdatedEvent.InputTuple, TokenUpdatedEvent.OutputTuple, TokenUpdatedEvent.OutputObject>;
    
    };
  }