/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface INoxEscrowReputationInterface extends Interface {
    getFunction(nameOrSignature: "addCompletedMilestone" | "getReputation" | "penalizeLostDispute" | "setBaseReputation" | "setFactory"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "BaseReputationConfigured" | "FactoryUpdated" | "ReputationUpdated"): EventFragment;

    encodeFunctionData(functionFragment: 'addCompletedMilestone', values: [AddressLike, BytesLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getReputation', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'penalizeLostDispute', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setBaseReputation', values: [BytesLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'setFactory', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'addCompletedMilestone', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getReputation', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'penalizeLostDispute', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setBaseReputation', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setFactory', data: BytesLike): Result;
  }

  
    export namespace BaseReputationConfiguredEvent {
      export type InputTuple = [baseHandle: BytesLike];
      export type OutputTuple = [baseHandle: string];
      export interface OutputObject {baseHandle: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace FactoryUpdatedEvent {
      export type InputTuple = [oldFactory: AddressLike, newFactory: AddressLike];
      export type OutputTuple = [oldFactory: string, newFactory: string];
      export interface OutputObject {oldFactory: string, newFactory: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ReputationUpdatedEvent {
      export type InputTuple = [freelancer: AddressLike, newReputation: BytesLike];
      export type OutputTuple = [freelancer: string, newReputation: string];
      export interface OutputObject {freelancer: string, newReputation: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface INoxEscrowReputation extends BaseContract {
    
    connect(runner?: ContractRunner | null): INoxEscrowReputation;
    waitForDeployment(): Promise<this>;

    interface: INoxEscrowReputationInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    addCompletedMilestone: TypedContractMethod<
      [freelancer: AddressLike, payout: BytesLike, rating: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    getReputation: TypedContractMethod<
      [freelancer: AddressLike, ],
      [string],
      'view'
    >
    

    
    penalizeLostDispute: TypedContractMethod<
      [freelancer: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setBaseReputation: TypedContractMethod<
      [_baseHandle: BytesLike, proof: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    setFactory: TypedContractMethod<
      [_newFactory: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'addCompletedMilestone'): TypedContractMethod<
      [freelancer: AddressLike, payout: BytesLike, rating: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getReputation'): TypedContractMethod<
      [freelancer: AddressLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'penalizeLostDispute'): TypedContractMethod<
      [freelancer: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setBaseReputation'): TypedContractMethod<
      [_baseHandle: BytesLike, proof: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setFactory'): TypedContractMethod<
      [_newFactory: AddressLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'BaseReputationConfigured'): TypedContractEvent<BaseReputationConfiguredEvent.InputTuple, BaseReputationConfiguredEvent.OutputTuple, BaseReputationConfiguredEvent.OutputObject>;
getEvent(key: 'FactoryUpdated'): TypedContractEvent<FactoryUpdatedEvent.InputTuple, FactoryUpdatedEvent.OutputTuple, FactoryUpdatedEvent.OutputObject>;
getEvent(key: 'ReputationUpdated'): TypedContractEvent<ReputationUpdatedEvent.InputTuple, ReputationUpdatedEvent.OutputTuple, ReputationUpdatedEvent.OutputObject>;

    filters: {
      
      'BaseReputationConfigured(bytes32)': TypedContractEvent<BaseReputationConfiguredEvent.InputTuple, BaseReputationConfiguredEvent.OutputTuple, BaseReputationConfiguredEvent.OutputObject>;
      BaseReputationConfigured: TypedContractEvent<BaseReputationConfiguredEvent.InputTuple, BaseReputationConfiguredEvent.OutputTuple, BaseReputationConfiguredEvent.OutputObject>;
    

      'FactoryUpdated(address,address)': TypedContractEvent<FactoryUpdatedEvent.InputTuple, FactoryUpdatedEvent.OutputTuple, FactoryUpdatedEvent.OutputObject>;
      FactoryUpdated: TypedContractEvent<FactoryUpdatedEvent.InputTuple, FactoryUpdatedEvent.OutputTuple, FactoryUpdatedEvent.OutputObject>;
    

      'ReputationUpdated(address,bytes32)': TypedContractEvent<ReputationUpdatedEvent.InputTuple, ReputationUpdatedEvent.OutputTuple, ReputationUpdatedEvent.OutputObject>;
      ReputationUpdated: TypedContractEvent<ReputationUpdatedEvent.InputTuple, ReputationUpdatedEvent.OutputTuple, ReputationUpdatedEvent.OutputObject>;
    
    };
  }